### ISSUE TITLE
java.lang.Error: Unresolved compilation problems:

### ISSUE THREAD

**Issue by SKRahulSK** [ktuukkan/marine-api#102]
I am trying to use the api in OSGI framework.

 While running it on linux distribution, I am getting below error.

java.lang.Error: Unresolved compilation problems:
        SerialPort cannot be resolved to a type
        The method getSerialPort() from the type SerialPortExample refers to the missing type SerialPort

        at net.sf.marineapi.example.SerialPortExample.init(SerialPortExample.java:155)
        at net.sf.marineapi.example.SerialPortExample.<init>(SerialPortExample.java:55)
        at gpsdnmea.Activator.start(Activator.java:22)
        at com.prosyst.mbs.impl.framework.BundleImpl.startIt(BundleImpl.java:5367)
        at com.prosyst.mbs.impl.framework.BundleImpl.simpleStart(BundleImpl.java:2276)
        at com.prosyst.mbs.impl.framework.BundleImpl.start0(BundleImpl.java:2151)
        at com.prosyst.mbs.impl.framework.BundleImpl.start0(BundleImpl.java:1992)
        at com.prosyst.mbs.impl.framework.BundleImpl.start(BundleImpl.java:1785)
        at com.prosyst.mbs.impl.framework.BundleImpl.start(BundleImpl.java:1762)
        at com.prosyst.mbs.impl.framework.BundleImpl.start(BundleImpl.java:1440)
        at com.prosyst.util.impl.commands.DefaultFrameworkPlugable.start(DefaultFrameworkPlugable.java:1398)
        at com.prosyst.util.impl.commands.DefaultFrameworkPlugable.start(DefaultFrameworkPlugable.java:1379)
        at com.prosyst.util.impl.commands.DefaultFrameworkPlugable.doExecuteCommand(DefaultFrameworkPlugable.java:437)
        at com.prosyst.util.pcommands.AbstractCommands.executeCommand(AbstractCommands.java:110)
        at com.prosyst.util.impl.parser.ParserServiceImpl.parseCommand(ParserServiceImpl.java:348)
        at com.prosyst.util.impl.console.ConsoleActivator.run(ConsoleActivator.java:204)
        at java.lang.Thread.run(Unknown Source)

**Comment by ktuukkan** [comment]
Just provide the serial port API in your classpath/pom or ignore the examples when compiling. The dependency is left out intentionally as it is not in the scope of the library.

Also notice, you shouldn't need to compile the whole library if you're just adding new parsers. If you are compiling because you have made changes in the code, please remember to follow LGPL.
