### ISSUE TITLE
openjdk 1.8 net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)         at net.sf.marineapi.nmea.event.AbstractSentenceListener.<init>(AbstractSentenceListener.java:77)

### ISSUE THREAD

**Issue by songhaonangit** [ktuukkan/marine-api#103]
2019-04-04 18:11:30.388 8411-8411/? E/AndroidRuntime:     at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
2019-04-04 18:11:30.388 8411-8411/? E/AndroidRuntime:     at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.nmea.event.AbstractSentenceListener.<init>(AbstractSentenceListener.java:77)

**Comment by ktuukkan** [comment]
Any context or additional info for this?

**Comment by ktuukkan** [comment]
Unable to reproduce, thus closing for now.
