### ISSUE TITLE
DataNotAvailableException in RMCParser with USB GPS receiver

### ISSUE THREAD

**Issue by drykovanov** [ktuukkan/marine-api#57]
We have cheap USB GPS receiver that seems to skip course information in GPRMC message
`$GPRMC,162945.000,A,6000.3763,N,03021.4359,E,0.00,,220816,,,A*7E`
This results to DataNotAvailableException: 

```
18:56:04.596 [Thread-8] WARN n.s.m.n.i.SentenceReader - Exception caught from SentenceListener
net.sf.marineapi.nmea.parser.DataNotAvailableException: Data not available
at net.sf.marineapi.nmea.parser.SentenceParser.getStringValue(SentenceParser.java:422) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.nmea.parser.SentenceParser.getDoubleValue(SentenceParser.java:382) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.nmea.parser.RMCParser.getCourse(RMCParser.java:85) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.provider.PositionProvider.createProviderEvent(PositionProvider.java:82) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.provider.PositionProvider.createProviderEvent(PositionProvider.java:53) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.provider.AbstractProvider.sentenceRead(AbstractProvider.java:217) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.nmea.io.SentenceReader.fireSentenceEvent(SentenceReader.java:197) ~[marineapi-0.8.1.jar:b20140608201434]
at net.sf.marineapi.nmea.io.AbstractDataReader.run(AbstractDataReader.java:86) [marineapi-0.8.1.jar:b20140608201434]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

**Comment by ktuukkan** [comment]
Hi, this issue has already been resolved in pull-request #51 and is included in 0.10.0-SNAPSHOT.
