### ISSUE TITLE
Option for less strictness (data first, correctness second)

### ISSUE THREAD

**Issue by akidee** [ktuukkan/marine-api#80]
Testing this with v0.9.0:

Much less sentence events than input events occur, although usable data is in the sentence. I want the parser to give me as much data as it can get while returning special values or null for invalid values.

I included the source code into my project and made the GGAParser class public, and then I just instantiated the parser without pre-checking for validity of the nmea argument. The result: An IllegalArgumentException is thrown from the sentence parser class - without giving further information:

	java.lang.IllegalArgumentException: Invalid data [$GPGGA,012356,...,...,2,07,1.6,276.0,M,48.0,M,,*42]
	at net.sf.marineapi.nmea.parser.SentenceParser.<init>(SentenceParser.java:88)
	at net.sf.marineapi.nmea.parser.SentenceParser.<init>(SentenceParser.java:143)
	at net.sf.marineapi.nmea.parser.SentenceParser.<init>(SentenceParser.java:176)
	at net.sf.marineapi.nmea.parser.PositionParser.<init>(PositionParser.java:46)
	at net.sf.marineapi.nmea.parser.GGAParser.<init>(GGAParser.java:62)

(Location removed)

Internally this seems to be what happens when using the reader in the regular way. I dont see a way to optionally disable this behavior. There may be a constant error on my device but if there is still usable data, I want to get it without the need to catch errors for the whole validation or parts of it.

At least it would be helpful to make the SentenceParser methods public, so that I can manually parse certain parts of a sentence. And give me more information about what is wrong in a sentence.

**Comment by ktuukkan** [comment]
The exception is related to general validation, so there's something wrong with the sentence formatting or maybe an incorrect checksum. Might also be wrong number of fields, as GGA may contain different number of fields depending on the NMEA version.

@akidee, can I have a clean sample of your data?
